### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by simenandre** [Wizhi/setup-buf#5]
Hello,

This package is no longer available on Github Marketplace (for some reason, might only be me). Anyway, can you release a new version and deploy it to the marketplace? :)

**Comment by wizhi** [comment]
Well that's odd.

I've made a new release for `v1` and published it to the marketplace.
Is it working for you now? :)

**Comment by simenandre** [comment]
Yes! 🎉

**Comment by simenandre** [comment]
@Wizhi Maybe you can cut a new release with the changes from #4 ?

**Comment by simenandre** [comment]
I really want to remove my fork 👍

**Comment by wizhi** [comment]
Sorry that slipped my mind - I've been using the `master` branch. :)

I've updated the `v1` tag and made a new release for it.
